OPT= -g --debug
#OPT= -g --debug --verbose
NPE=3

OUT_decl= decl1
#OUT_size= size1 size1-2 #size2 #sample #size1-err
### size2: assumed shape dummy coarray
#OUT_rt  =  inquiry
OUT_NG =  allo2NG

OUT_allo= allo1 allo3 allo2 
OUT_stat=#allo_stat

#OUT = times $(OUT_decl) $(OUT_size) $(OUT_allo) $(OUT_rt)
OUT=times times2

include ../Makefile.common

