#!/bin/bash

ifile="./xmpf_coarray_decl.f90"
ofile=`basename $0 ".sh"`
INCDIR="../include"

function output_entry_names {
    awk '
        $1 ~ /^interface|function|subroutine$/ &&
        $2 ~ /^[a-z][a-z0-9_][a-z0-9_][a-z0-9_]/ {
            split($2, token, "(")
            print token[1]
        }
        $1 != "end" && $1 !~ /^!/ &&
        $2 ~ /^interface|function|subroutine$/ &&
        $3 ~ /^[a-z][a-z0-9_][a-z0-9_][a-z0-9_]/ {
            split($3, token, "(")
            print token[1]
        }
    ' $1
}

function get_include_files {
    awk '
        $1 ~ /^include$/ &&
        $2 ~ /^"[a-zA-Z0-9_.]+"$/ {
            split($2, token, "\"")
            print token[2]
        }
    ' $1
}


## output header message
echo "# This file was automatically generated by $0"
echo "#   to be read by F-BackEnd/src/xcodeml/f/decompile/XfDecompileDomVisitor.java."
echo "# cf. bug report #493 for modification in the future"
echo "#"

## output interface/subroutine/function names in $ifile
output_entry_names $ifile

## get include file names in $ifile
incfiles=`get_include_files $ifile`

## output interface/subroutine/function names in all include files
for f in ${incfiles}; do
    output_entry_names ${INCDIR}/$f
done

exit
