! main program
      !! src: libxmpf/src/xmpf_misc.c
      !! incl. atexit, _XMP_init, FJMPI_Rdma_init, etc.
      call xmpf_init_all_

      !! These subroutines are written in /tmp/omni_traverse_nnnn.f90,
      !! which has automatically been generated by omni_traverse script.
      !! Driver/libexec/src/omni_traverse.in is the source file of 
      !! omni_traverse.
      call xmpf_traverse_module
      call xmpf_traverse_coarrayinit

      !! user's main program
      call xmpf_main

      !! src: libxmpf/src/xmpf_misc.c
      !! incl. FJMPI_Rdma_finalize(), _XMP_finalize, etc.
      call xmpf_finalize_all_
      end
