# Makefile.in generated by automake 1.14 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2013 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



am__is_gnu_make = test -n '$(MAKEFILE_LIST)' && test -n '$(MAKELEVEL)'
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/omni_xmp
pkgincludedir = $(includedir)/omni_xmp
pkglibdir = $(libdir)/omni_xmp
pkglibexecdir = $(libexecdir)/omni_xmp
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
target_triplet = x86_64-unknown-linux-gnu
#am__append_1 = libxmp/src_gpu
#am__append_2 = libacc/src libacc/include
#am__append_3 = ./Driver/atool
#  SUB_TESTDIRS += "local-view/post-wait/C" "local-view/coarray/C"
am__append_4 = "local-view/coarray/C"
#  SUB_TESTDIRS += "local-view/post-wait/C" "local-view/coarray/C"
#am__append_5 = "local-view/coarray/C"
subdir = .
DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/Makefile.am \
	$(top_srcdir)/configure $(am__configure_deps) \
	$(top_srcdir)/include/config.h.in \
	$(top_srcdir)/Driver/atool/src/include/nata/nata_config.h.in \
	$(top_srcdir)/release/debian/changelog.in \
	$(top_srcdir)/release/debian/control.in \
	$(top_srcdir)/release/debian/rules.in \
	$(top_srcdir)/release/xcalablemp.spec.in \
	$(top_srcdir)/release/make_rpm.sh.in \
	$(top_srcdir)/release/make_deb.sh.in \
	$(top_srcdir)/Driver/atool/mk/vars.mk.in \
	$(top_srcdir)/Driver/atool/Makefile.in \
	$(top_srcdir)/Driver/atool/src/lib/Makefile.in \
	$(top_srcdir)/Driver/atool/src/include/nata/Makefile.in \
	$(top_srcdir)/Driver/atool/src/include/nata/nata_platform.h.in \
	$(top_srcdir)/Driver/atool/src/cmd/Makefile.in \
	$(top_srcdir)/Driver/atool/src/cmd/paths.h.in \
	./buildutils/compile ./buildutils/config.guess \
	./buildutils/config.sub ./buildutils/depcomp \
	./buildutils/install-sh ./buildutils/missing \
	./buildutils/ylwrap ./buildutils/ltmain.sh \
	$(top_srcdir)/./buildutils/compile \
	$(top_srcdir)/./buildutils/config.guess \
	$(top_srcdir)/./buildutils/config.sub \
	$(top_srcdir)/./buildutils/install-sh \
	$(top_srcdir)/./buildutils/ltmain.sh \
	$(top_srcdir)/./buildutils/missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/buildutils/libtool.m4 \
	$(top_srcdir)/buildutils/ltoptions.m4 \
	$(top_srcdir)/buildutils/ltsugar.m4 \
	$(top_srcdir)/buildutils/ltversion.m4 \
	$(top_srcdir)/buildutils/lt~obsolete.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/include/config.h \
	$(top_builddir)/Driver/atool/src/include/nata/nata_config.h
CONFIG_CLEAN_FILES = release/debian/changelog release/debian/control \
	release/debian/rules release/xcalablemp.spec \
	release/make_rpm.sh release/make_deb.sh \
	Driver/atool/mk/vars.mk Driver/atool/Makefile \
	Driver/atool/src/lib/Makefile \
	Driver/atool/src/include/nata/Makefile \
	Driver/atool/src/include/nata/nata_platform.h \
	Driver/atool/src/cmd/Makefile Driver/atool/src/cmd/paths.h
CONFIG_CLEAN_VPATH_FILES =
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
depcomp =
am__depfiles_maybe =
SOURCES =
DIST_SOURCES =
RECURSIVE_TARGETS = all-recursive check-recursive cscopelist-recursive \
	ctags-recursive dvi-recursive html-recursive info-recursive \
	install-data-recursive install-dvi-recursive \
	install-exec-recursive install-html-recursive \
	install-info-recursive install-pdf-recursive \
	install-ps-recursive install-recursive installcheck-recursive \
	installdirs-recursive pdf-recursive ps-recursive \
	tags-recursive uninstall-recursive
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
am__recursive_targets = \
  $(RECURSIVE_TARGETS) \
  $(RECURSIVE_CLEAN_TARGETS) \
  $(am__extra_recursive_targets)
AM_RECURSIVE_TARGETS = $(am__recursive_targets:-recursive=) TAGS CTAGS \
	cscope distdir dist dist-all distcheck
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
DIST_SUBDIRS = XcodeML-Common C-FrontEnd/src C-BackEnd \
	F-FrontEnd/src F-BackEnd XcodeML-Exc-Tools \
	Driver/src libompc/src libompf/src libtlog/src_threads \
	libtlog/src_mpi libxmp/include libxmp/src \
	libxmp/src_threads libxmpf/include libxmpf/src \
	libxmp/src_gpu libacc/src libacc/include ./Driver/atool \
	$(am__empty)
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/mnakao/archives/omni-compiler/buildutils/missing aclocal-1.14
AIX_OPT = 
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
ANTCOM = JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64 /usr/bin/ant
API_FLAVOR = NATA_API_POSIX
AR = ar
ARFLAGS = cru
ATOOL_DIR = ./Driver/atool
AUTOCONF = ${SHELL} /home/mnakao/archives/omni-compiler/buildutils/missing autoconf
AUTOHEADER = ${SHELL} /home/mnakao/archives/omni-compiler/buildutils/missing autoheader
AUTOMAKE = ${SHELL} /home/mnakao/archives/omni-compiler/buildutils/missing automake-1.14
AWK = mawk
BASH = /bin/bash
BECC = mpicc
BECC_OMP_OPTION = -fopenmp
BECC_OPTION = -std=gnu99 -Wall -Wpointer-arith 
BEFC = mpif90
BEFC_MODINC = -J
BEFC_OPTION = 
CC = gcc
CCDEPMODE = depmode=gcc3
CC_LIB = gcc
CFLAGS =  -O2  -g -O2
CPP = gcc -E
CPPFLAGS = -DOMNI_CPU_X86_64 -DOMNI_OS_LINUX -DNDEBUG   
CPU = x86_64
CPUDEF = NATA_CPU_X86_64
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS =  -O2  -g -O2
CYGPATH_W = echo
C_BACKEND_DIR = C-BackEnd
C_FRONTEND_DIR = C-FrontEnd/src
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
ENABLE_ACC = 0
ENABLE_ATOOL = 0
EXEEXT = 
F2C_INT64_FLAGS = -DAllow_TYQUAD
FC = gfortran
FCFLAGS = -g -O2
FGREP = /bin/grep -F
FJRDMA = 
F_BACKEND_DIR = F-BackEnd
F_FRONTEND_DIR = F-FrontEnd/src
GASNET_CFLAGS = -O3 --param max-inline-insns-single=35000 --param inline-unit-growth=10000 --param large-function-growth=200000 -Winline
GASNET_CONDUIT = mpi
GASNET_CPPFLAGS = -DGASNET_SEQ -I/home/mnakao/work/GASNet-1.20.0/include -I/home/mnakao/work/GASNet-1.20.0/include/mpi-conduit -D_XMP_COARRAY_GASNET
GASNET_LDFLAGS = -O3 --param max-inline-insns-single=35000 --param inline-unit-growth=10000 --param large-function-growth=200000 -Winline
GASNET_LIBS = -L/home/mnakao/work/GASNet-1.20.0/lib -lgasnet-mpi-seq -lammpi -lrt -L/usr/lib/gcc/x86_64-linux-gnu/4.7 -lgcc -lm
GASNET_PREFIX = /home/mnakao/work/GASNet-1.20.0
GPGPU_PREFIX = /usr/local/cuda
GPU_CMD = nvcc
GREP = /bin/grep
INCLUDECOM = include
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
INT_ENUFF_FOR_VOIDP = unsigned long
IS_AIX = No
IS_CRAY = No
IS_PGCC = No
JARCOM = /usr/lib/jvm/java-7-openjdk-amd64/bin/jar
JAVACCOM = /usr/lib/jvm/java-7-openjdk-amd64/bin/javac
JAVACOM = java
JAVA_HOME = /usr/lib/jvm/java-7-openjdk-amd64
JAVA_OPT = -Xmx1024m
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = 
LEX = flex
LEXLIB = -lfl
LEX_OUTPUT_ROOT = lex.yy
LIBACC_DIR = libacc/src
LIBACC_HEADER_DIR = libacc/include
LIBOBJS = 
LIBOMPC_DIR = libompc/src
LIBOMPF_DIR = libompf/src
LIBS = -lm -lm 
LIBTLOG_DIR = libtlog/src_threads
LIBTLOG_MPI_DIR = libtlog/src_mpi
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBTOOL_DEPS = ./buildutils/ltmain.sh
LIBXML_PREFIX = /usr
LIBXMPF_DIR = libxmpf/src
LIBXMPF_HEADER_DIR = libxmpf/include
LIBXMP_DIR = libxmp/src
LIBXMP_GPU_DIR = libxmp/src_gpu
LIBXMP_HEADER_DIR = libxmp/include
LIBXMP_THREADS_DIR = libxmp/src_threads
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAINT = 
MAKE = make
MAKEINFO = ${SHELL} /home/mnakao/archives/omni-compiler/buildutils/missing makeinfo
MANIFEST_TOOL = :
MKDIR = mkdir -p
MKDIR_P = /bin/mkdir -p
MKRULESDIR = /home/mnakao/archives/omni-compiler/Driver/atool/mk
MM5TGT = 
NM = nm
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OMC_CONF_LNK_OPT = -fopenmp
OMC_CONF_LX2X_OPT = 
OMC_CONF_NTV_OPT = -std=gnu99 -Wno-implicit -Wno-attributes
OMDRIVER_DIR = Driver/src
OMF_CONF_LNK_OPT = -fopenmp -lgomp
OMF_CONF_LX2X_OPT = -gnu
OMF_CONF_NTV_OPT = -ffree-form
OMNI_HOME = /home/mnakao/work/xmp-trunk
OMP_LOCK_TYPE = mutex
OMP_THREAD_TYPE = pthread
OM_DRIVER_CONF_DIR = /home/mnakao/work/xmp-trunk/etc
OM_EXEC_CXX_LINKER = g++
OM_EXEC_C_COMPILER = mpicc
OM_EXEC_C_LINKER = mpicc
OM_EXEC_C_PP = mpicc -E
OM_EXEC_F_COMPILER = gfortran
OM_EXEC_F_LINKER = gfortran
OM_EXEC_F_PP = gfortran -E
OS = linux
OSDEF = NATA_OS_LINUX
OS_CFLAGS = 
OS_CPPFLAGS = -D_REENTRANT -D_GNU_SOURCE
OS_CXXFLAGS = 
OS_LDFLAGS = 
OS_LIBS = -lrt -lpthread
OTOOL = 
OTOOL64 = 
PACKAGE = omni_xmp
PACKAGE_BUGREPORT = xmp-users@hpcs.cs.tsukuba.ac.jp
PACKAGE_NAME = Omni Compiler
PACKAGE_STRING = Omni Compiler 0.8.0
PACKAGE_TARNAME = omni_xmp
PACKAGE_URL = 
PACKAGE_VERSION = 0.8.0
PATH_SEPARATOR = :
PERL5 = /usr/bin/perl
POW_LIB = 
PPTGT = 
RANLIB = ranlib
RM = rm -f
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
SIZEOF_DOUBLE = 8
SIZEOF_FLOAT = 4
SIZEOF_LONG_DOUBLE = 16
SIZEOF_UNSIGNED_CHAR = 1
SIZEOF_UNSIGNED_INT = 4
SIZEOF_UNSIGNED_LONG = 8
SIZEOF_UNSIGNED_LONG_LONG = 8
SIZEOF_UNSIGNED_SHORT = 2
SIZEOF_VOID_P = 8
SIZEOF__BOOL = 1
SR16000 = 
STRIP = strip
SUPERUX = 
TARGET_ARCH = POSIX
TOPDIR = /home/mnakao/archives/omni-compiler
TYPE_INT16 = short
TYPE_INT32 = int
TYPE_INT64 = long int
VERSION = 0.8.0
XCODEML_COMMON_DIR = XcodeML-Common
XCODEML_EXC_TOOLS_DIR = XcodeML-Exc-Tools
XMPPKG_CHANGELOG_DATE = Fri, 30 May 2014 18:40:27 +0900
XMPPKG_GROUP = Development Languages
XMPPKG_LICENSE = LGPLv2
XMPPKG_MAINTAINER = Hitoshi Murai <h-murai@riken.jp>

#install-data-local:
#	if test -e "./doc"; then\
#		test -z "${docdir}" || ${MKDIR_P} "${docdir}";\
#		cp -fr ./doc/* ${docdir}/; chmod -R 755 ${docdir}/*;\
#	fi
XMPPKG_NAME := "omni-compiler"
XMPPKG_PACKAGER = Hitoshi Murai <h-murai@riken.jp>
XMPPKG_PREFIX = 
XMPPKG_PRIORITY = extra
XMPPKG_RELEASE = r1640
XMPPKG_SECTION = devel
XMPPKG_SUMMARY = Omni Compiler Software
XMPPKG_URL = http://www.hpcs.cs.tsukuba.ac.jp/omni-compiler/
XMPPKG_VENDOR = Riken AICS and University of Tsukuba
XMPPKG_VERSION = 0.8.0
XMP_ENABLE_GPU = 0
YACC = byacc
YFLAGS = 
ZIPCOM = zip
abs_builddir = /home/mnakao/archives/omni-compiler
abs_srcdir = /home/mnakao/archives/omni-compiler
abs_top_builddir = /home/mnakao/archives/omni-compiler
abs_top_srcdir = /home/mnakao/archives/omni-compiler
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
ac_ct_FC = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
cppCmd = gfortran
datadir = ${datarootdir}
datarootdir = ${prefix}/share
doQReal = no
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
gmpIncOpt = 
gmpLibOpt = 
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/mnakao/archives/omni-compiler/buildutils/install-sh
isIBMJava6 = no
isSunJava6 = yes
javaType = sun
javadir = ${prefix}/share/xcalablemp
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
nativeCompiler = gfortran
oldincludedir = /usr/include
omniBinDir = /home/mnakao/work/xmp-trunk/bin/
omniDir = /home/mnakao/work/xmp-trunk
omniEtcDir = /home/mnakao/work/xmp-trunk/etc/
omniExpT = int
omniIncDir = /home/mnakao/work/xmp-trunk/include
omniLibDir = /home/mnakao/work/xmp-trunk/lib/
omniLimbT = int
omniQPrec = 
omniQRealFillGap = 
omniQRealPrecInLimb = 1
pdfdir = ${docdir}
prefix = /home/mnakao/work/xmp-trunk
program_transform_name = 
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target = x86_64-unknown-linux-gnu
target_alias = 
target_cpu = x86_64
target_os = linux-gnu
target_vendor = unknown
top_build_prefix = 
top_builddir = .
top_srcdir = .

# $TSUKUBA_Release: Omni OpenMP Compiler 3 $
# $TSUKUBA_Copyright:
#  PLEASE DESCRIBE LICENSE AGREEMENT HERE
#  $
SUBDIRS = XcodeML-Common C-FrontEnd/src \
	C-BackEnd F-FrontEnd/src \
	F-BackEnd XcodeML-Exc-Tools \
	Driver/src libompc/src libompf/src \
	libtlog/src_threads libtlog/src_mpi \
	libxmp/include libxmp/src \
	libxmp/src_threads libxmpf/include \
	libxmpf/src $(am__append_1) $(am__append_2) \
	$(am__append_3)
#SUBDIRS = XcodeML-Common C-FrontEnd/src \
#	C-BackEnd F-FrontEnd/src F-BackEnd \
#	XcodeML-Exc-Tools Driver/src \
#	libtlog/src_threads libtlog/src_mpi \
#	libxmp/include libxmp/src \
#	libxmp/src_threads libxmpf/include \
#	libxmpf/src $(am__append_1) $(am__append_2) \
#	$(am__append_3)
XMPPKG_TMPDIR_TOP := "/tmp/omni-compiler"
XMPPKG_TMPDIR := $(XMPPKG_TMPDIR_TOP)/$(shell mktemp -u --tmpdir=/)
DEB_VER_FILE = "/etc/debian_version"
RH_REL_FILE = "/etc/redhat-release"
BASE_TESTDIR = "tests/xcalablemp/"
SUB_TESTDIRS = "others/F" "global-view/shadow-reflect/C/" \
	"global-view/reduction/C" "global-view/reduction/F" \
	"global-view/task/C" "global-view/task/F" $(am__append_4) \
	$(am__append_5)
DELETABLES = \
	C-BackEnd/ant.properties \
	C-BackEnd/bin/C_Back \
	C-FrontEnd/src/c-exprcode.c \
	C-FrontEnd/src/c-exprcode.h \
	C-FrontEnd/src/c-parser.c \
	C-FrontEnd/src/c-parser.h \
	Driver/bin/omc2c \
	Driver/bin/omc2x \
	Driver/bin/omclinker \
	Driver/bin/omcnative \
	Driver/bin/omcpp \
	Driver/bin/omcx2x \
	Driver/bin/omf2f \
	Driver/bin/omf2x \
	Driver/bin/omflinker \
	Driver/bin/omfnative \
	Driver/bin/omfpp \
	Driver/bin/omfx2x \
	Driver/bin/oml2x \
	Driver/bin/omlinker \
	Driver/bin/omnative \
	Driver/bin/ompcc \
	Driver/bin/ompf90 \
	Driver/bin/ompp \
	Driver/bin/omx2c \
	Driver/bin/omx2f \
	Driver/bin/omx2l \
	Driver/bin/omx2x \
	Driver/bin/xmpcc \
	Driver/bin/xmpf90 \
	Driver/bin/omtranslate \
	Driver/etc/java.conf \
	Driver/etc/l2x.conf.openmp \
	Driver/etc/l2x.conf.xmp \
	Driver/etc/l2x.conf.xmpf \
	Driver/etc/l2x.conf.acc \
	Driver/etc/linker.conf.openmp \
	Driver/etc/linker.conf.xmp \
	Driver/etc/linker.conf.xmpf \
	Driver/etc/linker.conf.acc \
	Driver/etc/native.conf.openmp \
	Driver/etc/native.conf.xmp \
	Driver/etc/native.conf.xmpf \
	Driver/etc/native.conf.acc \
	Driver/etc/omc.conf \
	Driver/etc/omf.conf \
	Driver/etc/pp.conf.openmp \
	Driver/etc/pp.conf.xmp \
	Driver/etc/pp.conf.xmpf \
	Driver/etc/pp.conf.acc \
	Driver/etc/x2x.conf.openmp \
	Driver/etc/x2x.conf.xmp \
	Driver/etc/x2x.conf.xmpf \
	Driver/etc/x2x.conf.acc \
	Driver/etc/setup.conf \
	C-FrontEnd/src/c-token.c \
	F-BackEnd/ant.properties \
	F-BackEnd/bin/F_Back \
	F-BackEnd/bin/F_Trans \
	F-BackEnd/bin/F_Decomp \
	F-FrontEnd/src/C-exprcode.c \
	F-FrontEnd/src/C-exprcode.h \
	F-FrontEnd/src/F95-parser.c \
	F-FrontEnd/src/F95-parser.output \
	XcodeML-Common/ant.properties \
	XcodeML-Exc-Tools/ant.properties \
	XcodeML-Exc-Tools/src/exc/util/MachineDepConst.java \
	autom4te.cache/ \
	libtlog/src_mpi/bin/tlogview \
	libtlog/src_mpi/libtlog_mpi.a \
	libtlog/src_threads/libtlog.a \
	tests/C-test/Makefile \
	tests/F-test/OMP-test/Makefile \
	tests/clinpack/Makefile \
	tests/tiny/Makefile \
	$(XMPPKG_TMPDIR_TOP) \
	${XMPPKG_NAME}*.tar.gz \
	${XMPPKG_NAME}*.deb \
	${XMPPKG_NAME}*.rpm

all: all-recursive

.SUFFIXES:
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign --ignore-deps'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign --ignore-deps \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign --ignore-deps Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign --ignore-deps Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

include/config.h: include/stamp-h1
	@test -f $@ || rm -f include/stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) include/stamp-h1

include/stamp-h1: $(top_srcdir)/include/config.h.in $(top_builddir)/config.status
	@rm -f include/stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status include/config.h
$(top_srcdir)/include/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f include/stamp-h1
	touch $@

Driver/atool/src/include/nata/nata_config.h: Driver/atool/src/include/nata/stamp-h2
	@test -f $@ || rm -f Driver/atool/src/include/nata/stamp-h2
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) Driver/atool/src/include/nata/stamp-h2

Driver/atool/src/include/nata/stamp-h2: $(top_srcdir)/Driver/atool/src/include/nata/nata_config.h.in $(top_builddir)/config.status
	@rm -f Driver/atool/src/include/nata/stamp-h2
	cd $(top_builddir) && $(SHELL) ./config.status Driver/atool/src/include/nata/nata_config.h

distclean-hdr:
	-rm -f include/config.h include/stamp-h1 Driver/atool/src/include/nata/nata_config.h Driver/atool/src/include/nata/stamp-h2
release/debian/changelog: $(top_builddir)/config.status $(top_srcdir)/release/debian/changelog.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
release/debian/control: $(top_builddir)/config.status $(top_srcdir)/release/debian/control.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
release/debian/rules: $(top_builddir)/config.status $(top_srcdir)/release/debian/rules.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
release/xcalablemp.spec: $(top_builddir)/config.status $(top_srcdir)/release/xcalablemp.spec.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
release/make_rpm.sh: $(top_builddir)/config.status $(top_srcdir)/release/make_rpm.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
release/make_deb.sh: $(top_builddir)/config.status $(top_srcdir)/release/make_deb.sh.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
Driver/atool/mk/vars.mk: $(top_builddir)/config.status $(top_srcdir)/Driver/atool/mk/vars.mk.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
Driver/atool/Makefile: $(top_builddir)/config.status $(top_srcdir)/Driver/atool/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
Driver/atool/src/lib/Makefile: $(top_builddir)/config.status $(top_srcdir)/Driver/atool/src/lib/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
Driver/atool/src/include/nata/Makefile: $(top_builddir)/config.status $(top_srcdir)/Driver/atool/src/include/nata/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
Driver/atool/src/include/nata/nata_platform.h: $(top_builddir)/config.status $(top_srcdir)/Driver/atool/src/include/nata/nata_platform.h.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
Driver/atool/src/cmd/Makefile: $(top_builddir)/config.status $(top_srcdir)/Driver/atool/src/cmd/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
Driver/atool/src/cmd/paths.h: $(top_builddir)/config.status $(top_srcdir)/Driver/atool/src/cmd/paths.h.in
	cd $(top_builddir) && $(SHELL) ./config.status $@

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool config.lt

# This directory's subdirectories are mostly independent; you can cd
# into them and run 'make' without going through this Makefile.
# To change the values of 'make' variables: instead of editing Makefiles,
# (1) if the variable is set in 'config.status', edit 'config.status'
#     (which will cause the Makefiles to be regenerated when you run 'make');
# (2) otherwise, pass the desired values on the 'make' command line.
$(am__recursive_targets):
	@fail=; \
	if $(am__make_keepgoing); then \
	  failcom='fail=yes'; \
	else \
	  failcom='exit 1'; \
	fi; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-recursive
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-recursive

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-recursive

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    $(am__make_dryrun) \
	      || test -d "$(distdir)/$$subdir" \
	      || $(MKDIR_P) "$(distdir)/$$subdir" \
	      || exit 1; \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile
installdirs: installdirs-recursive
installdirs-am:
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-generic clean-libtool clean-local mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -f Makefile
distclean-am: clean-am distclean-generic distclean-hdr \
	distclean-libtool distclean-local distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am:

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am:

install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man:

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-generic mostlyclean-libtool

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am:

.MAKE: $(am__recursive_targets) install-am install-strip

.PHONY: $(am__recursive_targets) CTAGS GTAGS TAGS all all-am \
	am--refresh check check-am clean clean-cscope clean-generic \
	clean-libtool clean-local cscope cscopelist-am ctags ctags-am \
	dist dist-all dist-bzip2 dist-gzip dist-lzip dist-shar \
	dist-tarZ dist-xz dist-zip distcheck distclean \
	distclean-generic distclean-hdr distclean-libtool \
	distclean-local distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am install-man \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	installdirs-am maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-generic mostlyclean-libtool pdf pdf-am \
	ps ps-am tags tags-am uninstall uninstall-am


release-rpm:
	if test -f $(RH_REL_FILE) ; then \
		mkdir -p $(XMPPKG_TMPDIR_TOP); \
		$(SHELL) release/make_rpm.sh $(CURDIR) $(XMPPKG_TMPDIR_TOP); \
		rm -rf $(XMPPKG_TMPDIR_TOP); \
	fi

release-deb:
	if test -f $(DEB_VER_FILE) ; then \
		mkdir -p $(XMPPKG_TMPDIR); \
		$(SHELL) release/make_deb.sh $(CURDIR) $(XMPPKG_TMPDIR); \
		rm -rf $(XMPPKG_TMPDIR_TOP); \
	fi

release: release-rpm release-deb

tests: tests-dummy
tests-dummy:
	@for dir in $(SUB_TESTDIRS); do \
	  make -C $(BASE_TESTDIR)$$dir; \
	  if [ $$? -ne 0 ]; then \
	    exit 1; \
	  fi; \
	done

clean-tests:
	@for dir in $(SUB_TESTDIRS); do \
	  make clean -C $(BASE_TESTDIR)$$dir; \
	done

run-tests:
	@for dir in $(SUB_TESTDIRS); do \
	  make run -C $(BASE_TESTDIR)$$dir; \
	  if [ $$? -ne 0 ]; then \
	    exit 1; \
	  fi; \
	done

clean-local:
	rm -rf autom4te.cache
	find . -type f \( \
		-name '*~' -o \
		-name '*.core' \
	\) -exec rm -f {} \;

distclean-local:
	if test ! -z "$(DELETABLES)"; then \
		rm -rf $(DELETABLES) ; \
	fi	

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
