
      MODULE ISO_FORTRAN_ENV
        TYPE LOCK_TYPE
        END type LOCK_TYPE
        INTEGER, PARAMETER :: ATOMIC_INT_KIND = 8
        INTEGER, PARAMETER :: ATOMIC_LOGICAL_KIND = 8
      END MODULE ISO_FORTRAN_ENV
