mpirun -np 3 allo1.x
mpirun -np 3 allo3.x
mpirun -np 3 allodeallo.x
mpirun -np 3 allo_hiloop.x
mpirun -np 3 allo_loop2.x
mpirun -np 3 allo_pipo3.x
mpirun -np 3 bug418-2.x
mpirun -np 3 bug418.x
mpirun -np 3 bug468.x
mpirun -np 3 cobound.x
mpirun -np 3 decl3.x
mpirun -np 3 image_index1.x
mpirun -np 3 image_index2.x
mpirun -np 3 image_index.x
mpirun -np 3 this_image.x
