#OPT= --debug
#OPT= -g --debug --verbose
NPE=3

OUT_intrin=lbound.x #intrin1.x
OUT_param=  param3.x param1.x param2.x param4.x
OUT_bug=bug456-2.x bug457-2.x # bug456.x bug457.x

OUT=$(OUT_intrin) $(OUT_param) $(OUT_bug)

include ../Makefile.common
