!! This file is for making xmp_constant_fmod.f90
!! Run: cpp -E -I$(OMNI_HONE)/include xmp_constant_f.f90 -o xmp_constant_fmod.f90
!! 
#include "xmp_constant.h"
#define DEF_F_CONST(F_NAME, VALUE)  \
  integer, parameter ::  F_NAME = VALUE
  
DEF_F_CONST(XMP_BOOL,_XMP_N_TYPE_BOOL)
DEF_F_CONST(  XMP_CHAR,	_XMP_N_TYPE_CHAR)
DEF_F_CONST(  XMP_UNSIGNED_CHAR,  _XMP_N_TYPE_UNSIGNED_CHAR)
DEF_F_CONST(  XMP_SHORT, 		_XMP_N_TYPE_SHORT)
DEF_F_CONST(  XMP_UNSIGNED_SHORT, _XMP_N_TYPE_UNSIGNED_SHORT)
DEF_F_CONST(  XMP_INT, 		_XMP_N_TYPE_INT)
DEF_F_CONST(  XMP_UNSIGNED_INT, 	_XMP_N_TYPE_UNSIGNED_INT)
DEF_F_CONST(  XMP_LONG, 		_XMP_N_TYPE_LONG)
DEF_F_CONST(  XMP_UNSIGNED_LONG, 	_XMP_N_TYPE_UNSIGNED_LONG)
DEF_F_CONST(  XMP_LONGLONG, 	_XMP_N_TYPE_LONGLONG)
DEF_F_CONST(  XMP_UNSIGNED_LONGLONG, 	_XMP_N_TYPE_UNSIGNED_LONGLONG)
DEF_F_CONST(  XMP_FLOAT, 		_XMP_N_TYPE_FLOAT)
DEF_F_CONST(  XMP_DOUBLE, 	_XMP_N_TYPE_DOUBLE)
DEF_F_CONST(  XMP_LONG_DOUBLE,  	_XMP_N_TYPE_LONG_DOUBLE)

DEF_F_CONST(  XMP_SUM, _XMP_N_REDUCE_SUM)
DEF_F_CONST(  XMP_PROD, _XMP_N_REDUCE_PROD)
DEF_F_CONST(  XMP_BAND, _XMP_N_REDUCE_BAND)
DEF_F_CONST(  XMP_LAND, _XMP_N_REDUCE_LAND)
DEF_F_CONST(  XMP_BOR, _XMP_N_REDUCE_BOR)
DEF_F_CONST(  XMP_LOR, _XMP_N_REDUCE_LOR)
DEF_F_CONST(  XMP_BXOR,_XMP_N_REDUCE_BXOR)
DEF_F_CONST(  XMP_LXOR, _XMP_N_REDUCE_LXOR)
DEF_F_CONST(  XMP_MAX, _XMP_N_REDUCE_MAX)
DEF_F_CONST(  XMP_MIN, _XMP_N_REDUCE_MIN)
DEF_F_CONST(  XMP_FIRSTMAX, _XMP_N_REDUCE_FIRSTMAX)
DEF_F_CONST(  XMP_FIRSTMIN, _XMP_N_REDUCE_FIRSTMIN)
DEF_F_CONST(  XMP_LASTMAX, _XMP_N_REDUCE_LASTMAX)
DEF_F_CONST(  XMP_LASTMIN, _XMP_N_REDUCE_LASTMIN)
DEF_F_CONST(  XMP_EQV, _XMP_N_REDUCE_EQV)
DEF_F_CONST(  XMP_NEQV, _XMP_N_REDUCE_NEQV)
DEF_F_CONST(  XMP_MINUS, _XMP_N_REDUCE_MINUS)
DEF_F_CONST(  XMP_MAXLOC, _XMP_N_REDUCE_MAXLOC)
DEF_F_CONST(  XMP_MINLOC, _XMP_N_REDUCE_MINLOC)


