#ifndef _XCALABLEMP_CONSTANT
#define _XCALABLEMP_CONSTANT

// defined in exc.xcalablemp.XMPtemplate
#define _XCALABLEMP_N_DIST_DUPLICATION			100
#define _XCALABLEMP_N_DIST_BLOCK			101
#define _XCALABLEMP_N_DIST_CYCLIC			102

// defined in exc.object.BasicType
#define _XCALABLEMP_N_TYPE_BOOL				202
#define _XCALABLEMP_N_TYPE_CHAR				203
#define _XCALABLEMP_N_TYPE_UNSIGNED_CHAR		204
#define _XCALABLEMP_N_TYPE_SHORT			205
#define _XCALABLEMP_N_TYPE_UNSIGNED_SHORT		206
#define _XCALABLEMP_N_TYPE_INT				207
#define _XCALABLEMP_N_TYPE_UNSIGNED_INT			208
#define _XCALABLEMP_N_TYPE_LONG				209
#define _XCALABLEMP_N_TYPE_UNSIGNED_LONG		210
#define _XCALABLEMP_N_TYPE_LONGLONG			211
#define _XCALABLEMP_N_TYPE_UNSIGNED_LONGLONG		212
#define _XCALABLEMP_N_TYPE_FLOAT			213
#define _XCALABLEMP_N_TYPE_DOUBLE			214
#define _XCALABLEMP_N_TYPE_LONG_DOUBLE			215
#define _XCALABLEMP_N_TYPE_FLOAT_IMAGINARY		216
#define _XCALABLEMP_N_TYPE_DOUBLE_IMAGINARY		217
#define _XCALABLEMP_N_TYPE_LONG_DOUBLE_IMAGINARY	218
#define _XCALABLEMP_N_TYPE_FLOAT_COMPLEX		219
#define _XCALABLEMP_N_TYPE_DOUBLE_COMPLEX		220
#define _XCALABLEMP_N_TYPE_LONG_DOUBLE_COMPLEX		221

// defined in exc.xcalablemp.XMPcollective
#define _XCALABLEMP_N_REDUCE_SUM			300
#define _XCALABLEMP_N_REDUCE_PROD			301

// defined in exc.xcalablemp.XMPshadow
#define _XCALABLEMP_N_SHADOW_NONE			400
#define _XCALABLEMP_N_SHADOW_NORMAL			401
#define _XCALABLEMP_N_SHADOW_FULL			402

#endif // _XCALABLEMP_CONSTANT
