#OPT= --debug
#OPT= -g --debug --verbose
NPE=3

OUT_basic  = struct_align.x alloc0.x #alloc1.x #put_compo1.x get_compo1.x get_compo2.x #get1.x #put1.x  putget1.x
#OUT_arg    = aarg1.x
#OUT_mod    = mod1.x

OUT = $(OUT_basic) $(OUT_arg) $(OUT_mod)

include ../Makefile.common
