# This file is included from */Makefile files.

SRC= $(OUT:%.x=%.f90)
RESULT=$(SRC:.f90=.result)
.SUFFIXES: .x .f90 .xmod

OUT4= $(OUT:%.x=%.x4)
OUT6= $(OUT:%.x=%.x6)
OUT7= $(OUT:%.x=%.x7)
OUT7g= $(OUT:%.x=%.x7g)
RESULT4=$(RESULT:.result=.result4)
RESULT6=$(RESULT:.result=.result6)
RESULT7=$(RESULT:.result=.result7)
RESULT7g=$(RESULT:.result=.result7g)

.f90.x:
	xmpf90 $(OPT) -o $@ $<

.c.x:
	xmpcc $(OPT) -o $@ $<

%.x4:  %.f90
	xmpf90 $(OPT) --Wx-fcoarray=4 -o $@ $<

%.x6:  %.f90
	xmpf90 $(OPT) --Wx-fcoarray=6 -o $@ $<

%.x7:  %.f90
	xmpf90 $(OPT) --Wx-fcoarray=7 -o $@ $<

%.x7g:  %.f90
	xmpf90 $(OPT) --Wx-fcoarray=7g -o $@ $<

%.result: %.x
	export XMP_ONESIDED_HEAP_SIZE=70M; mpirun -np $(NPE) ./$<

%.result4: %.x4
	export XMP_ONESIDED_HEAP_SIZE=70M; mpirun -np $(NPE) ./$<

%.result6: %.x6
	export XMP_ONESIDED_HEAP_SIZE=70M; mpirun -np $(NPE) ./$<

%.result7: %.x7
	export XMP_ONESIDED_HEAP_SIZE=70M; mpirun -np $(NPE) ./$<

%.result7g: %.x7g
	export XMP_ONESIDED_HEAP_SIZE=70M; mpirun -np $(NPE) ./$<

%.result: %.f90
	xmpf90 $(OPT) -o $*.x $<
	export XMP_ONESIDED_HEAP_SIZE=70M; mpirun -np $(NPE) ./$*.x

%.result: %.c
	xmpcc $(OPT) -o $*.x $<
	export XMP_ONESIDED_HEAP_SIZE=70M; mpirun -np $(NPE) ./$*.x
	cat $@

RUN/%.x:: %.x
	cp $< $@

RUN/%.x4:: %.x4
	cp $< $@

RUN/%.x6:: %.x6
	cp $< $@

RUN/%.x7:: %.x7
	cp $< $@

RUN/%.x7g:: %.x7g
	cp $< $@

RUN/%.x:: 
	touch $@

RUN/%.x4:: 
	touch $@

RUN/%.x6:: 
	touch $@

RUN/%.x7:: 
	touch $@

RUN/%.x7g:: 
	touch $@

### compile test programs
all:     $(OUT)

all4:     $(OUT4)

all6:     $(OUT6)

all7:     $(OUT7)

all7g:     $(OUT7g)

### execute on local environment
run:	$(RESULT)

run4:	$(RESULT4)

run6:	$(RESULT6)

run7:
	@echo '*** use run7g for GASNet environment ***'

run7g:	$(RESULT7g)

### prepare to execute on K/FX10
submit: all RUN RUN/go.sh $(OUT:%=RUN/%)
	cd RUN; pjsub go.sh

submit4: all4 RUN RUN/go4.sh $(OUT4:%=RUN/%)
	cd RUN; pjsub go4.sh

submit6: all6 RUN RUN/go6.sh $(OUT6:%=RUN/%)
	cd RUN; pjsub go6.sh

submit7: all7 RUN RUN/go7.sh $(OUT7:%=RUN/%)
	cd RUN; pjsub go7.sh

RUN:
	mkdir RUN

RUN/go.sh: go.template Makefile
	sed "s/@OUT@/$(OUT)/" $< >$@

RUN/go4.sh: go.template Makefile
	sed "s/@OUT@/$(OUT4)/" $< >$@

RUN/go6.sh: go.template Makefile
	sed "s/@OUT@/$(OUT6)/" $< >$@

RUN/go7.sh: go.template Makefile
	sed "s/@OUT@/$(OUT7)/" $< >$@

showlog:
	cat RUN/go.sh.e* RUN/go.sh.o*

### clean
cleanlog:
	rm -rf RUN

clean: cleanlog
	rm -f *~ *.o *.x *.result a.out
	rm -rf __omni_tmp__/
	rm -f omni_traverse*.o
	rm -f $(OUT:%=RUN/%)
	rm -f *.mod *.xmod
	rm -f *.x4 *.result4
	rm -f *.x6 *.result6
	rm -f *.x7 *.result7
	rm -f *.x7g *.result7g
