#OPT= --debug
#OPT= -g --debug --verbose
NPE=3

OUT_OK    = a1d1-3 a1d1-2 a1d1-1 a6d3 a6d4-2  a6d3-1 a6d3-2 a3d3 a2d2  a2d2-1-1 a2d2-1-5  s-2 s-1 a1d1-4 a6d4-1  a0d0-2 a0d0-3
OUT_NG    = a2d0 a2d1  a2d1-2 a2d1-3
OUT_bound = l0-3okB
OUT_NGB   = a2d2-2NGB
#OUT_type  = a1d1-typeNG
#OUT_err  = l0-2NG

#OUT=$(OUT_OK) $(OUT_NG) $(OUT_bound) $(OUT_type) $(OUT_NGB)
OUT=$(OUT_OK) $(OUT_NG) $(OUT_bound) $(OUT_NGB)

include ../Makefile.common
