#!/bin/sh
#PJM --rsc-list "rscgrp=large"
#PJM --rsc-list "node=8x8x8"
#PJM --rsc-list "elapse=00:10:00"
#PJM --stg-transfiles all
#PJM --mpi "use-rankdir"
#PJM --stgin "rank=* ../mpi ../caf-* ./stdin* %r:./"
##PJM --stgout "rank=* %r:./Fprofd_stati/* ./job%j/Fprofd_stati/"
##PJM -s

. /work/system/Env_base

#OPT="-mca mpi_print_stats 1 -mca coll_tuned_use_6d_algorithm 1 -mca coll_tuned_prealloc_size 2600"

OUT="mpi caf-wide caf-narrow caf-fit mpi"
MODEL=L
SHAPE=888
NODES=512

for m in ${MODEL}; do
    for f in ${OUT}; do
        echo
        echo "****************************************************"
        echo "himenoBMT $f $m ${SHAPE} ($m-model/${NODES}-nodes)"
        echo "****************************************************"
        mpiexec -stdin ./stdin${m}${SHAPE} -n ${NODES} ./$f
    done
done


