#!/bin/bash

#-------------------------------------------------------
#  generator for xmp_lib_coarray_reduction.h
#-------------------------------------------------------

#--------------------
#  sub
#--------------------
echo72 () {
    str="$1                                                                        "
    str=`echo "$str" | cut -c -72`"&"
    echo "$str"
}

print_function() {
    tk=$1
    typekind=$2
    echo "      subroutine xmpf_co_${OP}${DIM}d_${tk}(source, result)"

    case ${DIM} in
        0)  echo    "      ${typekind}, intent(in)  :: source" ;;
        1)  echo    "      ${typekind}, intent(in)  :: source(:)" ;;
        *)  echo -n "      ${typekind}, intent(in)  :: source(:"
            for i in `seq 2 ${DIM}`; do
                echo -n ',:'
            done
            echo ')' ;;
    esac

    case ${DIM} in
        0)  echo    "      ${typekind}, intent(out) :: result" ;;
        1)  echo    "      ${typekind}, intent(out) :: result(:)" ;;
        *)  echo -n "      ${typekind}, intent(out) :: result(:"
            for i in `seq 2 ${DIM}`; do
                echo -n ',:'
            done
            echo ')' ;;
    esac

    echo "      end function"
    echo
}


#--------------------
#  main
#--------------------
echo "!! This file is automatically generated by $0"

TARGET=$1

for OP in sum max min
do
    echo
    echo "!-------------------------------------------------------"
    echo "      interface co_${OP}"
    echo "!-------------------------------------------------------"
    echo

for DIM in `seq 0 7`
do
    if test "sxace-nec-superux" != "$TARGET"; then    ## integer(2) cannot be used on SX-ACE
	print_function i2  "integer(2)"
    fi
    print_function i4  "integer(4)"      
    print_function i8  "integer(8)"

    print_function r4  "real(4)"         
    print_function r8  "real(8)"         
    echo "!!!  real(kind=16) is not supported in XMP/F"
    echo

    if test ${OP} == sum; then
        print_function z8  "complex(4)"      
        print_function z16 "complex(8)"      
        echo "!!!  complex(kind=16) (32bytes) is not supported in XMP/F"
        echo
    fi

done

    echo "      end interface"
    echo
done

exit
