MODULE N
  IMPLICIT NONE
  PRIVATE
  INTERFACE f
    FUNCTION g()
    REAL :: g
    END FUNCTION
  END INTERFACE
CONTAINS
  SUBROUTINE sbr()
    INTERFACE f
      FUNCTION g()
      REAL :: g
      END FUNCTION
    END INTERFACE
  END SUBROUTINE sbr
END MODULE N
