#!/bin/sh

# $Id$
# $RWC_Release$
# $RWC_Copyright$


PROG=./exit
ERRORS=0


OMP_NUM_THREADS=2

$EXEC $PROG -i0 -c0
if [ $? != 0 ]; then
  ERRORS=1
fi

$EXEC $PROG -i0 -c1
if [ $? != 1 ]; then
  ERRORS=1
fi

$EXEC $PROG -i0 -c2
if [ $? != 2 ]; then
  ERRORS=1
fi

if [ $ERRORS = 0 ]; then
  echo "exit 001 : SUCCESS"
else
  echo "exit 001 : FAILED"
fi
