/*
 * $TSUKUBA_Release: Omni OpenMP Compiler 3 $
 * $TSUKUBA_Copyright:
 *  PLEASE DESCRIBE LICENSE AGREEMENT HERE
 *  $
 */
#ifndef _C_ACC_H
#define _C_ACC_H

enum ACC_pragma {
  ACC_PARALLEL,
  ACC_END_PARALLEL,
  ACC_DATA,
  ACC_END_DATA,
  ACC_LOOP, //no ACC_END_LOOP
  ACC_PARALLEL_LOOP,
  ACC_END_PARALLEL_LOOP,
  ACC_KERNELS_LOOP,
  ACC_END_KERNELS_LOOP,
  ACC_ATOMIC,
  ACC_END_ATOMIC,
  ACC_WAIT,
  ACC_KERNELS,
  ACC_END_KERNELS,
  ACC_CACHE,
  ACC_ROUTINE,
  ACC_ENTER_DATA,
  ACC_EXIT_DATA,
  ACC_HOST_DATA,
  ACC_END_HOST_DATA,
  ACC_DECLARE,
  ACC_UPDATE_D,
  ACC_INIT,
  ACC_SHUTDOWN,
  ACC_SET,

  ACC_DIR_END
};

enum ACC_pragma_clause {
  ACC_IF = 500,
  ACC_WAIT_ARG,
  ACC_CACHE_ARG,
  ACC_ROUTINE_ARG,

  //data clause
  ACC_COPY,
  ACC_COPYIN,
  ACC_COPYOUT,
  ACC_CREATE,
  ACC_PRESENT,
  ACC_PRESENT_OR_COPY,
  ACC_PRESENT_OR_COPYIN,
  ACC_PRESENT_OR_COPYOUT,
  ACC_PRESENT_OR_CREATE,
  ACC_DEVICEPTR,
  //end data clause

  ACC_ASYNC,
  ACC_WAIT_C,
  ACC_DEVICE_TYPE,

  //compute clause
  ACC_NUM_GANGS,
  ACC_NUM_WORKERS,
  ACC_VECTOR_LENGTH,

  //reductions
  ACC_REDUCTION_PLUS,
  ACC_REDUCTION_MUL,
  ACC_REDUCTION_MAX,
  ACC_REDUCTION_MIN,
  ACC_REDUCTION_BITAND,
  ACC_REDUCTION_BITOR,
  ACC_REDUCTION_BITXOR,
  ACC_REDUCTION_LOGAND,
  ACC_REDUCTION_LOGOR,
  ACC_REDUCTION_EQV,
  ACC_REDUCTION_NEQV,

  //for parallel
  ACC_PRIVATE,
  ACC_FIRSTPRIVATE,
  ACC_DEFAULT,
  ACC_NONE,

  //for loop
  ACC_COLLAPSE,
  ACC_GANG,
  ACC_WORKER,
  ACC_VECTOR,
  ACC_STATIC,
  ACC_SEQ,
  ACC_AUTO,
  ACC_TILE,
  ACC_INDEPENDENT,

  ACC_BIND,
  ACC_NOHOST,

  //atomic clause
  ACC_READ,
  ACC_WRITE,
  ACC_UPDATE,
  ACC_CAPTURE,
  ACC_DELETE,
  ACC_FINALIZE,

  ACC_USE_DEVICE,

  ACC_DEVICE_RESIDENT,
  ACC_LINK,

  ACC_HOST,
  ACC_DEVICE,
  ACC_IF_PRESENT,

  ACC_DEVICE_NUM,
  ACC_DEFAULT_ASYNC,

  //others
  ACC_ASTERISK,
  ACC_COMMONBLOCK,

  ACC_CLAUSE_END
};

#endif
