#!/bin/sh

if [ $# -ne 1 ]; then
  echo "Please add version number to argument."
  echo "e.g.) ./mkdist 0.8"
  exit 1
fi

PACKAGE_NAME=omnicompiler-$1

if [ ! -e configure.ac ]; then
    pwd
    echo execute this script in top directory
    exit 1
fi

if [ -e "./config.log" ]; then
    echo execute this script before configure
    exit 1
fi

###################
# Check CopyRight
###################
CPYRHTTXT="./release/copyright.txt"
if [ ! -e "${CPYRHTTXT}" ]; then
     echo needed copyright.txt.
     exit 1
fi

echo "---"
cat $CPYRHTTXT
echo "---"
echo "Is this $CPYRHTTXT OK ? (Yes/No)"
while true; do
  read answer
  case $answer in
  yes)
    break
    ;;
  Yes)
    break
    ;;
  no)
    exit 1
    ;;
  *)
    echo "Type Yes or No."
    # LOOP
    ;;
  esac
done

###################
# Check Release Note
###################
RELNAMETXT="./release/releasename.txt"
if [ ! -e "${RELNAMETXT}" ]; then
     echo needed ${RELNAMETXT}.
     exit 1
fi
echo "---"
cat $RELNAMETXT
echo "---"
echo "Is this $RELNAMETXT OK ? (Yes/No)"
while true; do
  read answer
  case $answer in
  yes)
    break
    ;;
  Yes)
    break
    ;;
  no)
    exit 1
    ;;
  *)
    echo "Type Yes or No."
    # LOOP
    ;;
  esac
done

###################
# Create Pakcage
###################
WORK_DIR=../`basename $PWD`-dist
PACKAGE_DIR=$WORK_DIR/$PACKAGE_NAME
DOC_DIR=$PACKAGE_DIR/doc

echo autogen.sh
./autogen.sh

echo delete dist dir
rm -rf $WORK_DIR
mkdir $WORK_DIR

echo copy whole files
cp -r . $PACKAGE_DIR

# expands keywords for a releasement.
echo expand a copyright and a release name.
./release/expand_tsukuba_keyword \
  -ignore release/ignore_expand_keyword.txt\
  -copyright ${CPYRHTTXT} \
  -release "`head -n1 ${RELNAMETXT}`"\
  $PACKAGE_DIR 

echo delete .svn dirs
find $PACKAGE_DIR -name \.svn -exec rm -rf \{\} \; 2> /dev/null

echo configure
./configure > /dev/null

echo touch Makefile.in
find $PACKAGE_DIR -name Makefile.in -exec touch \{\} \;

sleep 1

echo touch configure
touch $PACKAGE_DIR/configure

echo archiving
cd $WORK_DIR
tar cjf $PACKAGE_NAME.tar.bz2 $PACKAGE_NAME

echo completed
echo "Created package is " $WORK_DIR/$PACKAGE_NAME.tar.bz2

