echo autosyncall1.x --------------; mpirun -np 3 autosyncall1.x
echo bug403OK.x --------------; mpirun -np 3 bug403OK.x
echo bug403.x --------------; mpirun -np 3 bug403.x
echo bug451.x --------------; mpirun -np 3 bug451.x
echo bug460OK.x --------------; mpirun -np 3 bug460OK.x
echo bug472G1.x --------------; mpirun -np 3 bug472G1.x
echo bug472G2.x --------------; mpirun -np 3 bug472G2.x
echo bug472.x --------------; mpirun -np 3 bug472.x
echo dummyarg-1.x --------------; mpirun -np 3 dummyarg-1.x
echo dummyarg-2.x --------------; mpirun -np 3 dummyarg-2.x
echo dummyarg-3.x --------------; mpirun -np 3 dummyarg-3.x
echo finalize.x --------------; mpirun -np 3 finalize.x
echo host1.x --------------; mpirun -np 3 host1.x
echo host2.x --------------; mpirun -np 3 host2.x
echo mod1.x --------------; mpirun -np 3 mod1.x
echo modalloc.x --------------; mpirun -np 3 modalloc.x
echo nestModule.x --------------; mpirun -np 3 nestModule.x
echo sakagami457.x --------------; mpirun -np 3 sakagami457.x
echo sakagami458-join.x --------------; mpirun -np 3 sakagami458-join.x
echo sakagami459-join.x --------------; mpirun -np 3 sakagami459-join.x
echo sakagami460-2.x --------------; mpirun -np 3 sakagami460-2.x
echo sakagami460-join.x --------------; mpirun -np 3 sakagami460-join.x
