echo  allo1.x --------------; mpirun -np 3 allo1.x
echo  allo3.x --------------; mpirun -np 3 allo3.x
echo  allodeallo.x --------------; mpirun -np 3 allodeallo.x
echo  allo_hiloop.x --------------; mpirun -np 3 allo_hiloop.x
echo  allo_loop2.x --------------; mpirun -np 3 allo_loop2.x
echo  allo_pipo3.x --------------; mpirun -np 3 allo_pipo3.x
echo  bug418-2.x --------------; mpirun -np 3 bug418-2.x
echo  bug418.x --------------; mpirun -np 3 bug418.x
echo  bug468.x --------------; mpirun -np 3 bug468.x
echo  cobound.x --------------; mpirun -np 3 cobound.x
echo  decl3.x --------------; mpirun -np 3 decl3.x
echo  image_index0.x --------------; mpirun -np 3 image_index0.x
echo  this_image.x --------------; mpirun -np 3 this_image.x
