echo a1d1-1.x --------------; mpirun -np 3 a1d1-1.x
echo a1d1-4.x --------------; mpirun -np 3 a1d1-4.x
echo a1d1-5.x --------------; mpirun -np 3 a1d1-5.x
echo a6d3-1.x --------------; mpirun -np 3 a6d3-1.x
echo actualarg-2.x --------------; mpirun -np 3 actualarg-2.x
echo actualarg-3.x --------------; mpirun -np 3 actualarg-3.x
echo actualarg.x --------------; mpirun -np 3 actualarg.x
echo axd0-1.x --------------; mpirun -np 3 axd0-1.x
echo axd1-1.x --------------; mpirun -np 3 axd1-1.x
echo axd2-1.x --------------; mpirun -np 3 axd2-1.x
echo cn1-1NGB.x --------------; mpirun -np 3 cn1-1NGB.x
echo cn1-2okB.x --------------; mpirun -np 3 cn1-2okB.x
echo cn1d1-writeNGB.x --------------; mpirun -np 3 cn1d1-writeNGB.x
echo module-1.x --------------; mpirun -np 3 module-1.x
echo module-2.x --------------; mpirun -np 3 module-2.x
echo nest.x --------------; mpirun -np 3 nest.x
echo putget-2NGB.x --------------; mpirun -np 3 putget-2NGB.x
echo putget-3NGB.x --------------; mpirun -np 3 putget-3NGB.x
echo putget-4.x --------------; mpirun -np 3 putget-4.x
echo putget-5.x --------------; mpirun -np 3 putget-5.x
echo putget-6NGB.x --------------; mpirun -np 3 putget-6NGB.x
echo triplet.x --------------; mpirun -np 3 triplet.x
