#OPT= --debug
#OPT= -g --debug --verbose
NPE=3

#OUT_param=param1 param3 param2 param4
OUT_param= param3.x #param1.x
#OUT_intrin= intrin1.x
OUT_intrin=lbound.x
OUT_bug=bug456.x bug456-2.x

OUT=$(OUT_intrin) $(OUT_param) $(OUT_bug)

include ../F/Makefile.common
