OPT= -g --debug
#OPT= -g --debug --verbose
NPE=3

OUT_darg   = dummyarg-1 dummyarg-2
OUT_host   = host2 host1
#host3 host2-1 ... problem in gfortran?

#OUT=putget-2NGB dummyarg-1
OUT = $(OUT_host) $(OUT_darg)

include ../Makefile.common
