#ifndef _ACC_GPU_CONSTANT
#define _ACC_GPU_CONSTANT

#define _ACC_GPU_COPY_HOST_TO_DEVICE 400
#define _ACC_GPU_COPY_DEVICE_TO_HOST 401

#define _ACC_GPU_MPOOL_BLOCK_SIZE (1024*1024*1)
#define _ACC_GPU_MPOOL_NUM_BLOCKS 8

#define _ACC_GPU_MAX_NUM_BLOCKS 65535

#endif //_ACC_GPU_CONSTANT
