#OPT= --debug
#OPT= -g --debug --verbose
NPE= 8

#fatal: cannot convert Xcode to XcodeML.
#costmtInSpdo.x costmtInSpdo-2.x

OUT=this_image.x this_image2.x coarray_dir.x #image_dir.x


include ../Makefile.common
