#OPT= --debug
#OPT= -g --debug --verbose
NPE= 8

#fatal: cannot convert Xcode to XcodeML.
#costmtInSpdo.x costmtInSpdo-2.x

OUT_1=this_image.x this_image_nodesegment.x
OUT_2=this_image2.x 
OUT_SYNC=sync1.x
OUT_DIR= coarray_dir.x #image_dir.x

OUT= $(OUT_1) $(OUT_2) $(OUT_SYNC) #$(OUT_DIR)


include ../Makefile.common
