#!/bin/sh

#PJM --rsc-list "rscgrp=small"
##------------------------------------- customize from here
#PJM --rsc-list "node=6x6x6"
#PJM --rsc-list "elapse=00:20:00"
##------------------------------------- to here
#PJM --stg-transfiles all
#PJM --mpi "use-rankdir"
#PJM --stgin "rank=* ../*.x ./STDIN/* %r:./"
##PJM --stgout "rank=* %r:./Fprofd_stati/* ./job%j/Fprofd_stati/"
#PJM -s

. /work/system/Env_base

#OPT="-mca mpi_print_stats 1 -mca coll_tuned_use_6d_algorithm 1 -mca coll_tuned_prealloc_size 2600"

##------------------------------------- customize from here
EXE="mpi.x caf-wide.x caf-narrow.x caf-fit.x"
MODEL="M L XL"
SHAPE=666
NODES=216
##------------------------------------- to here

for m in ${MODEL}; do
    for f in ${EXE}; do
        echo
        echo "****************************************************"
        echo "himenoBMT $f $m ${SHAPE} ($m-model/${NODES}-nodes)"
        echo "****************************************************"
        mpiexec -stdin ./stdin${m}${SHAPE} -n ${NODES} ./$f
    done
done


